import type { Metadata } from "next";

// La meta data de la pagina se puede definir en el archivo page.tsx, 
// es importante porque se puede definir la metadata de la pagina en el archivo de la pagina
// esto es util cuando un usuario busca informacion de la pagina en el buscador
export const metadata: Metadata = {
    title: "Seo tittle about",
    description: "Generated by create next app",
    keywords: ["about", "about page", "about us"],
};


export default function AboutPage() {
    return (
        <div>
            <span className="text-7xl">AboutPages</span>
        </div>
    )
}
