import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Seo tittle pricing",
    description: "Generated by create next app",
    keywords: ["pricing", "pricing page", "precios"],
};


export default function PricingPage() {
    return (
        <div>
            <span className="text-7xl">PricingPage</span>
        </div>
    )
}
