import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Seo tittle contact",
    description: "Generated by create next app",
    keywords: ["contact", "contact page", "contact us"],
};

export default function ContactPage() {
    return (
        <div>
            <span className="text-7xl">ContactPage</span>
        </div>
    )
}
