import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Seo tittle contact",
    description: "Generated by create next app",
    keywords: ["contact", "contact page", "contact us"],
};

const contacts = [
    {
        name: "John Doe",
        email: "john.doe@sasf.net"
    },
    {
        name: "Jane Doe",
        email: "jane.doe@sasf.net"
    },
    {
        name: "Kelvin Doe",
        email: "kelvin.doe@sasf.net"
    }
];

export default function ContactPage() {
    return (
        <>
            {contacts.map((contact, index) => (
                <div key={index}>
                    <span className="text-2xl">{contact.name}</span>
                    <span className="text-2xl">{contact.email}</span>
                </div>
            ))}
        </>
    );
}
